# Generated by Django 2.2.9 on 2020-01-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servedPizz', '0002_auto_20200112_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=1)),
                ('size', models.CharField(choices=[('mmedium', 'medium'), ('small', 'small'), ('large', 'large')], max_length=10)),
                ('pizza', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servedPizz.servedPizza')),
            ],
        ),
    ]
