# Generated by Django 2.2.9 on 2020-01-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200112_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custumerName', models.CharField(max_length=65)),
                ('fullAdress', models.CharField(max_length=255)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orderpizzaitem',
            name='toOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
