# Generated by Django 2.2.9 on 2020-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200112_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderObjects',
            field=models.ManyToManyField(to='orders.orderPizzaItem'),
        ),
    ]
