# Generated by Django 2.2.9 on 2020-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servedPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('meet', 'meet'), ('cheese', 'cheese'), ('chicken', 'chicken')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, max_length=6)),
            ],
        ),
    ]
