# Generated by Django 2.2.9 on 2020-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servedPizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servedpizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=6),
        ),
    ]
