# Generated by Django 2.2.9 on 2020-01-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servedPizz', '0002_auto_20200112_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servedpizza',
            name='price',
        ),
    ]
